name: Deploy PROD

on:
  release:
    types: [published]

jobs:
  update-deployment:
    runs-on: ubuntu-latest
    environment: prod
    # needs: docker-build-and-push
    # if: success()

    steps:
      - name: 리포지토리 체크아웃
        uses: actions/checkout@v3
        with:
          repository: ${{ vars.ORG_GITOPS_REPOSITORY }} # team-joytas/wooco-gitops
          token: ${{ secrets.ORG_GITOPS_PAT }}

      - name: 이미지 버전 변경 # kustomize cli 대신 yq 사용
        uses: mikefarah/yq@v4.44.3
        with:
          cmd: >
            yq -i
            '.spec.template.spec.containers[0].image =
            "${{ secrets.DOCKER_HUB_REPOSITORY }}:${{ github.event.release.tag_name }}"'
            ./${{ vars.ORG_GITOPS_PROD_DEPLOYMENT_PATH }}

      # https://github.com/simonw/simonw/issues/11
      - name: 커밋 & 푸시
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "release: Deploy ${{ github.event.release.tag_name }} wooco spring app"
          git remote set-url origin https://${{ secrets.ORG_GITOPS_PAT }}@github.com/${{ vars.ORG_GITOPS_REPOSITORY }}
          git push --set-upstream origin HEAD
